repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Format code with Ruff
        entry: 'poetry run ruff format .'
        verbose: true
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-check
        name: Lint code with Ruff
        entry: 'poetry run ruff check --fix'
        verbose: true
        language: system
        types: [python]
        pass_filenames: false
      - id: ty
        name: Run ty type checker
        entry: 'poetry run ty check'
        verbose: true
        language: system
        types: [python]
        pass_filenames: false
